# Generated by Django 3.0.6 on 2020-05-17 22:52

from django.db import migrations, models

# the model gets migrated  (created) in the database which its db.sqlite3 in the main folder
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', max_length=200, upload_to='', width_field='image_width')),
                ('qoute', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
