# Generated by Django 3.0.6 on 2020-05-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20200518_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='qoute',
            field=models.TextField(max_length=200),
        ),
    ]
