# Generated by Django 3.0.6 on 2020-05-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20200519_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='qoute',
            field=models.CharField(max_length=50),
        ),
    ]
